---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Setting Global Options
```{r}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, fig.width = 10, fig.height = 5, 
                      fig.keep = 'all', fig.path = 'figures\ ', dev = 'png' )

```
## Loading and preprocessing the data
```{r}
library(ggplot2)
library(ggthemes)

path = getwd()
unzip("repdata_data_activity.zip", exdir = path)
activity <- read.csv("activity.csv")

activity$date <- as.POSIXct(activity$date, "%Y%m%d")

day <- weekdays(activity$date)

activity <- cbind(activity, day)

summary (activity)
```

## What is mean total number of steps taken per day?
```{r}
activity_total_steps <- with(activity, aggregate(steps, by = list(date), FUN = sum, na.rm = TRUE))
names(activity_total_steps) <- c("date","steps")
hist(activity_total_steps$steps, main = "Total Number of Steps Taken Per Day", xlab = "Total Steps Taken Per Day", ylab = "Number of Days", col = "lightblue", 
     ylim = c(0,20), breaks = seq(0, 25000, by = 2500))
```

```{r}
totalStepsSummary <- c(mean(activity_total_steps$steps), median(activity_total_steps$steps))
print(totalStepsSummary)
```

## What is the average daily activity pattern?
```{r}
average_daily_activity <- aggregate(activity$steps, by=list(activity$interval), FUN=mean, na.rm=TRUE)
names(average_daily_activity) <- c("interval", "mean")
plot(average_daily_activity$interval, average_daily_activity$mean, type = "l", col="lightblue", lwd = 2, xlab="Interval", ylab="Average number of steps", main="Average number of steps per intervals")
```

```{r}
average_daily_activity[which.max(average_daily_activity$mean), ]$interval
```


## Imputing missing values
```{r}
sum(is.na(activity$steps))
imputed_steps <- average_daily_activity$mean[match(activity$interval, average_daily_activity$interval)]
activity_imputed <- transform(activity, steps = ifelse(is.na(activity$steps), yes = imputed_steps, no = activity$steps))
total_steps_imputed <- aggregate(steps ~ date, activity_imputed, sum)
names(total_steps_imputed) <- c("date", "daily_steps")
hist(total_steps_imputed$daily_steps, col = "lightblue", xlab = "Total steps per day", ylim = c(0,30), main = "Total number of steps taken each day", breaks = seq(0,25000,by=2500))
```

```{r}
mean(total_steps_imputed$daily_steps)
median(total_steps_imputed$daily_steps)
```


## Are there differences in activity patterns between weekdays and weekends?
```{r}
activity$date <- as.Date(strptime(activity$date, format="%Y-%m-%d"))
activity$datetype <- sapply(activity$date, function(x) {
        if (weekdays(x) == "Saturday" | weekdays(x) =="Sunday") 
                {y <- "Weekend"} else 
                {y <- "Weekday"}
                y
        })
```

```{r}
activity_by_date <- aggregate(steps~interval + datetype, activity, mean, na.rm = TRUE)
plot<- ggplot(activity_by_date, aes(x = interval , y = steps, color = datetype)) +
       geom_line() +
       labs(title = "Average Daily Steps By Type of Day", x = "Interval", y = "Average Number of Steps") +
       facet_wrap(~datetype, ncol = 1, nrow=2)
print(plot)
```
